theme = "amberwood"

[editor]
line-number = "relative"

[editor.lsp]
auto-signature-help = false

[keys.normal]
"C-c" = ["keep_primary_selection", "collapse_selection"]

[keys.normal.g]
c = "toggle_comments"
u = "switch_to_lowercase"
U = "switch_to_uppercase"

[keys.insert]
"C-c" = ["keep_primary_selection", "collapse_selection", "normal_mode"]

[keys.select]
"C-c" = ["normal_mode", "keep_primary_selection", "collapse_selection"]

[keys.select.g]
u = "switch_to_lowercase"
U = "switch_to_uppercase"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

